"""Add is_read to Message

Revision ID: 227da8aec73f
Revises: ab0885899fd7
Create Date: 2025-07-28 12:01:19.792334

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '227da8aec73f'
down_revision = 'ab0885899fd7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_read', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.drop_column('is_read')

    # ### end Alembic commands ###
